### ISSUE TITLE
PermissionUtls.isGranted() is not correct when you forbid permission in system settings

### ISSUE THREAD

**Issue by LengBoCode** [rebus007/PermissionUtils#15]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Permission Utils.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Permission Utils version: `x.x.x`
 - Device OS version: `7.0`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5X`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```

###### Reproduction Steps

1.
2.
3.

**Comment by raphaelbussa** [comment]
Need more info, like some snippet code or other info
