### ISSUE TITLE
FullCallback not triggered for denied and denied for ever

### ISSUE THREAD

**Issue by janakagamini** [rebus007/PermissionUtils#3]
Below is what my FullCallback implementation looks like.     

```
new FullCallback() {@
    Override
    public void result(ArrayList < PermissionEnum > permissionsGranted,
        ArrayList < PermissionEnum > permissionsDenied,
        ArrayList < PermissionEnum > permissionsDeniedForever,
        ArrayList < PermissionEnum > permissionsAsked) {

        Log.d("DEBUG", "call back"); // Not printed if I deny, or deny forever.

        for (PermissionEnum permissionEnum: permissionsGranted) {
            if (permissionEnum.equals(PermissionEnum.CAMERA)) {
                Log.d("DEBUG", "granted!");
            }
        }

        for (PermissionEnum permissionEnum: permissionsDenied) {
            if (permissionEnum.equals(PermissionEnum.CAMERA)) {
                Log.d("DEBUG", "denied!");
            }
        }

        for (PermissionEnum permissionEnum: permissionsDeniedForever) {
            if (permissionEnum.equals(PermissionEnum.CAMERA)) {
                Log.d("DEBUG", "denied for ever!");
            }
        }

        for (PermissionEnum permissionEnum: permissionsAsked) {
            if (permissionEnum.equals(PermissionEnum.CAMERA)) {
                Log.d("DEBUG", "asked!");
            }
        }
    }
}
```

**Comment by raphaelbussa** [comment]
In the sample it works, can you send me the complete implementation so that it can test the same situation?

**Comment by ApofisXII** [comment]
Same issue!

**Comment by raphaelbussa** [comment]
I need some complete implementation.

**Comment by Johnsonmaung** [comment]
Same problem in Fragment too...

**Comment by Johnsonmaung** [comment]
`public class FragmentNearby extends BaseFragment
implements NearbyMVPView, FullCallback, OnMapReadyCallback {

/*
0 - Retry
1 - No Data
*/ int error_type = 0;

//@Bind(R.id.map) GoogleMap googleMap;
@Bind(R.id.llContent) LinearLayout llContent;
@Bind(R.id.progress) ProgressBar progressBar;
@Bind(R.id.linearMessage) LinearLayout linearMessage;
@Bind(R.id.imgMessage) ImageView imgMessage;
@Bind(R.id.tvMessage) TextView tvMessage;
@Bind(R.id.btnMessage) Button btnMessage;

View rootView;
GoogleMap googleMap;
NearByPresenter presenter;

public static FragmentNearby newInstance() {
FragmentNearby fragment = new FragmentNearby();
return fragment;
}

@Override public Context getContext() {
return getActivity();
}

@Override public void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
presenter = new NearByPresenter();
presenter.attachView(this);
}

@Override public View onCreateView(LayoutInflater inflater, ViewGroup container,
Bundle savedInstanceState) {
//Recycle for map Fragment
if (rootView != null) {
ViewGroup parent = (ViewGroup) rootView.getParent();
if (parent != null) parent.removeView(rootView);
}
try {
rootView = inflater.inflate(R.layout.fragment_nearby, container, false);
ButterKnife.bind(this, rootView);
SupportMapFragment mapFragment =
(SupportMapFragment) getChildFragmentManager().findFragmentById(map);
mapFragment.getMapAsync(this);
} catch (InflateException e) {
/* map is already there, just return view as it is */
}
return rootView;
}

@Override public void onDestroy() {
presenter.detachView();
super.onDestroy();
}

@Override public void onDestroyView() {
super.onDestroyView();
ButterKnife.unbind(this);
}

@Override public void onMapReady(GoogleMap googleMap) {
this.googleMap = googleMap;
presenter.getNearByLocation();
}

@OnClick(R.id.btnMessage) void ActionClick() {
if (error_type == 0) {
PermissionManager.with(getActivity())
.key(9001)
.permission(PermissionEnum.ACCESS_FINE_LOCATION)
.askAgain(false)
.askAgainCallback(new AskAgainCallback() {
@Override public void showRequestPermission(UserResponse response) {
showDialog(response);
}
})
.callback(this)
.ask();
} else if (error_type == 1) {
//go to home
presenter.getNearByLocation();
}
}

@Override public void showMessage(int message) {
error_type = message;
if (message == 0) {
tvMessage.setText("Need permission!");
btnMessage.setText("Grant");
} else if (message == 1) {
tvMessage.setText("No product in cart.");
btnMessage.setText("Go Shopping");
}
llContent.setVisibility(View.GONE);
progressBar.setVisibility(View.GONE);
linearMessage.setVisibility(View.VISIBLE);
}

@Override public void showProgress() {
llContent.setVisibility(View.GONE);
progressBar.setVisibility(View.VISIBLE);
linearMessage.setVisibility(View.GONE);
}

@Override public void showContent() {
try {
//GeoJsonLayer layer = new GeoJsonLayer(googleMap, new JSONObject(geo));
GeoJsonLayer layer = new GeoJsonLayer(googleMap, R.raw.geo, getActivity());
layer.addLayerToMap();
/LatLng yangon = new LatLng(16.8661, 96.1951);
googleMap.moveCamera(CameraUpdateFactory.newLatLng(yangon));/
//CameraPosition cameraPosition = new CameraPosition.Builder().target(yangon).zoom(14).build();
//googleMap.animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition));
/LatLngBounds bound =
new LatLngBounds(new LatLng(96.135751, 16.778411), new LatLng(96.172158, 16.769463));/
//googleMap.moveCamera(CameraUpdateFactory.newLatLngZoom(layer.getBoundingBox().getCenter(), 12));
googleMap.moveCamera(CameraUpdateFactory.newLatLngBounds(layer.getBoundingBox(), 0));
layer.setOnFeatureClickListener(new GeoJsonLayer.GeoJsonOnFeatureClickListener() {
@Override public void onFeatureClick(GeoJsonFeature feature) {
Toast.makeText(getActivity(), "Feature clicked: " + feature.getProperty("name"),
Toast.LENGTH_SHORT).show();
}
});
//layer.clearLayer();
} catch (IOException e) {
e.printStackTrace();
} catch (JSONException e) {
e.printStackTrace();
}
llContent.setVisibility(View.VISIBLE);
progressBar.setVisibility(View.GONE);
linearMessage.setVisibility(View.GONE);
}

@Override public void result(ArrayList permissionsGranted,
ArrayList permissionsDenied,
ArrayList permissionsDeniedForever,
ArrayList permissionsAsked) {

LogUtils.e("Hey!");

for (PermissionEnum permissionEnum : permissionsGranted) {
  if (permissionEnum.equals(PermissionEnum.ACCESS_FINE_LOCATION)) {
    LogUtils.e("granted!");
  }
}

for (PermissionEnum permissionEnum : permissionsDenied) {
  if (permissionEnum.equals(PermissionEnum.ACCESS_FINE_LOCATION)) {
    LogUtils.e("denied!");
  }
}

for (PermissionEnum permissionEnum : permissionsDeniedForever) {
  if (permissionEnum.equals(PermissionEnum.ACCESS_FINE_LOCATION)) {
    LogUtils.e("denied for ever!");
  }
}

for (PermissionEnum permissionEnum : permissionsAsked) {
  if (permissionEnum.equals(PermissionEnum.ACCESS_FINE_LOCATION)) {
    LogUtils.e("asked!");
  }
}
}

@Override public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,
@NonNull int[] grantResults) {
super.onRequestPermissionsResult(requestCode, permissions, grantResults);
PermissionManager.handleResult(requestCode, permissions, grantResults);
}

private void showDialog(final AskAgainCallback.UserResponse response) {
new AlertDialog.Builder(getActivity()).setTitle("Permission needed")
.setMessage("This app realy need to use this permission, you wont to authorize it?")
.setPositiveButton("OK", new DialogInterface.OnClickListener() {
@Override public void onClick(DialogInterface dialogInterface, int i) {
response.result(true);
}
})
.setNegativeButton("NOT NOW", new DialogInterface.OnClickListener() {
@Override public void onClick(DialogInterface dialogInterface, int i) {
response.result(false);
}
})
.setCancelable(false)
.show();
}
}
``

**Comment by raphaelbussa** [comment]
Issue not found...
