### ISSUE TITLE
fragment？

### ISSUE THREAD

**Issue by leon2017** [rebus007/PermissionUtils#5]
sorry,This will use the exception in the Fragment.....

**Comment by raphaelbussa** [comment]
???

**Comment by leon2017** [comment]
sorry,this PermissionUtils cannot be used in the fragment.......

**Comment by raphaelbussa** [comment]
Is not correct, you can, what is your problem?

**Comment by raphaelbussa** [comment]
I have just update the libs, now a section of sample app work with a Fragment.
Something like this

``` Java
@Override
public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
    Fragment fragment = fragmentManager.findFragmentByTag(SECOND_FRAGMENT);
    if (fragment != null) {
        fragment.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }
    super.onRequestPermissionsResult(requestCode, permissions, grantResults);
}
```

Now in the fragment with tag SECOND_FRAGMENT you can use the lib

Full code: [FragmentActivity.java](https://github.com/rebus007/PermissionUtils/blob/master/sample/src/main/java/rebus/permissionutils/sample/FragmentActivity.java) [SecondFragment.java](https://github.com/rebus007/PermissionUtils/blob/master/sample/src/main/java/rebus/permissionutils/sample/SecondFragment.java)

**Comment by leon2017** [comment]
oh,this is prefect,thx
