### ISSUE TITLE
can init the request using Fragment(in support library)

### ISSUE THREAD

**Issue by richardissuperman** [rebus007/PermissionUtils#6]
currently the util just support using context, hence if using Fragment.getContext() as the parameter to init the permission util we still have to put         PermissionManager.handleResult(requestCode, permissions, grantResults);
in the activity's onRequestPermissionsResult()

**Comment by raphaelbussa** [comment]
It will be fixed in the next version

**Comment by raphaelbussa** [comment]
Check version 1.0.8 https://github.com/rebus007/PermissionUtils/releases/tag/1.0.8

**Comment by richardissuperman** [comment]
thanks!!
