### ISSUE TITLE
Leak in PermissionManager instance

### ISSUE THREAD

**Issue by sudansh** [rebus007/PermissionUtils#9]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of Permission Utils.
- [ x] I have given my issue a non-generic title.
- [ x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Permission Utils version: `1.0.9`
 - Device OS version: `7.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `S7 Edge`

Also, please wrap Java with correct syntax highlighting.

```java
PermissionManager.with(HomeActivity.this)
						 .key(RC_CAMERA)
						 .permission(PermissionEnum.CAMERA)
						 .askAgain(true)
						 .askAgainCallback(new AskAgainCallback() {
							 @Override
							 public void showRequestPermission(UserResponse response) {
							 }
						 })
						 .callback(new FullCallback() {
							 @Override
							 public void result(ArrayList<PermissionEnum> permissionsGranted, ArrayList<PermissionEnum> permissionsDenied,
												ArrayList<PermissionEnum> permissionsDeniedForever, ArrayList<PermissionEnum> permissionsAsked) {
								 if (!permissionsGranted.isEmpty() && permissionsGranted.contains(PermissionEnum.CAMERA)) {
									 startPublishWirecastPage();
								 } else if (!permissionsDeniedForever.isEmpty()
										 || permissionsDeniedForever.contains(PermissionEnum.CAMERA)
										 ) {
								 }
							 }
						 })
						 .ask();
```

###### Reproduction Steps

1.  Use Permission Manager anywhere
2.
3.

###### Expected Result
Should not leak

###### Actual Result
Leakcanary shows a leak in PermissionManager instance

**Comment by raphaelbussa** [comment]
Is a context reference to the static permission manager instance. For implementation convenience had remained there. Shortly there comes a new version version that resolves. The implementation of the manager changes to obviate the static reference of the context

thanks

**Comment by raphaelbussa** [comment]
check new beta version
https://github.com/rebus007/PermissionUtils/releases/tag/2.0.0-BETA-1

**Comment by raphaelbussa** [comment]
@sudansh you have tried new beta version?

**Comment by sudansh** [comment]
Yes, it seems to be working now. No Leaks. Thanks
Will wait for the stable release of 2.0.0

**Comment by raphaelbussa** [comment]
Perfect, thanks for telling me
